name: Deploy 3-Tier App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup SSH Access
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add EC2 to known hosts
      run: |
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
          rsync -avz --exclude '.git' --exclude 'node_modules' ./ ubuntu@${{ secrets.HOST }}:/home/ubuntu/Ai-recognitionApp

    - name: Connect and deploy
      run: |
          ssh ubuntu@${{ secrets.HOST }} << 'EOF'
            cd /home/ubuntu/Ai-recognitionApp
            echo "${{ secrets.ENV_LOCAL }}" > .env.local
            docker-compose down
            docker-compose up --build -d
          EOF